Repository codesquad-members-2021/todo-list, pull requests merged in 2021-04, with the labels that each got.

#3 [[FE]][Pyro, Kyle, Jenny] 04-08 진행중
  README.md
  backend/README.md
  frontend/README.md
  frontend/todo-frontend/.gitignore
  frontend/todo-frontend/README.md
  frontend/todo-frontend/package.json
  frontend/todo-frontend/public/index.html
  frontend/todo-frontend/public/robots.txt
  frontend/todo-frontend/src/App.css
  frontend/todo-frontend/src/App.js
  frontend/todo-frontend/src/App.test.js
  frontend/todo-frontend/src/component/TodoTemplate.jsx
  frontend/todo-frontend/src/component/todoHeader/TodoHeader.jsx
  frontend/todo-frontend/src/component/todoMain/TodoMain.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/TodoItem.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/TodoList.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/TodoListForm.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/todoList.module.css
  frontend/todo-frontend/src/component/todoMain/todoMain.module.css
  frontend/todo-frontend/src/index.css
  frontend/todo-frontend/src/index.js
  frontend/todo-frontend/src/setupTests.js
  frontend/todo-frontend/yarn.lock
Labels: review-fe

#5 [FE][Team-17 : BeTasy] CRA 환경설정 & LayOut 1차 구현
  README.md
  todo/.gitignore
  todo/README.md
  todo/package-lock.json
  todo/package.json
  todo/public/favicon.ico
  todo/public/index.html
  todo/src/App.js
  todo/src/App.scss
  todo/src/components/atoms/Form/index.jsx
  todo/src/components/atoms/Image/index.jsx
  todo/src/components/atoms/Input/index.jsx
  todo/src/components/atoms/Label/index.jsx
  todo/src/components/atoms/MediumButton/index.jsx
  todo/src/components/atoms/SmallButton/index.jsx
  todo/src/components/atoms/Span/index.jsx
  todo/src/components/molecules/ButtonList/index.jsx
  todo/src/components/molecules/Header/index.jsx
  todo/src/components/molecules/HistoryItem/index.jsx
  todo/src/components/molecules/HistoryList/index.jsx
  todo/src/components/molecules/TodoList/index.jsx
  todo/src/components/molecules/TodoListItem/index.jsx
  todo/src/components/molecules/TodoTitle/index.jsx
  todo/src/images/closeButton.svg
  todo/src/images/hamburgerButtonIcon.png
  todo/src/images/plusButton.svg
  todo/src/images/userIcon.png
  todo/src/index.js
Labels: review-fe

#10 [BE][team-1 tree & 이노] spring boot 프로젝트 설정, mockup API 생성
  .gitignore
  BE/.gitignore
  BE/.idea/.gitignore
  BE/.idea/.name
  BE/.idea/compiler.xml
  BE/.idea/jarRepositories.xml
  BE/.idea/misc.xml
  BE/.idea/vcs.xml
  BE/HELP.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/example/todolist/TodoListApplication.java
  BE/src/main/java/com/example/todolist/domain/timeline/Timeline.java
  BE/src/main/java/com/example/todolist/domain/timeline/TimelineRepository.java
  BE/src/main/java/com/example/todolist/domain/user/User.java
  BE/src/main/java/com/example/todolist/domain/user/UserRepository.java
  BE/src/main/java/com/example/todolist/domain/work/Work.java
  BE/src/main/java/com/example/todolist/domain/work/WorkRepository.java
  BE/src/main/java/com/example/todolist/exception/EntityNotCreateException.java
  BE/src/main/java/com/example/todolist/exception/ErrorMessage.java
  BE/src/main/java/com/example/todolist/exception/UserAccountException.java
  BE/src/main/java/com/example/todolist/service/UserService.java
  BE/src/main/java/com/example/todolist/web/TimelineController.java
  BE/src/main/java/com/example/todolist/web/UserController.java
  BE/src/main/java/com/example/todolist/web/WorkController.java
  BE/src/main/java/com/example/todolist/web/dto/RequestLoginUserDto.java
  BE/src/main/java/com/example/todolist/web/dto/RequestSignInUserDto.java
  BE/src/main/java/com/example/todolist/web/dto/ResponseLoginUserDto.java
  BE/src/main/java/com/example/todolist/web/utils/HttpSessionUtils.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/example/todolist/TodoListApplicationTests.java
Labels: review-be

#11 [FE][Neis, Pengdori, Ppamppam] todo-list 1주차
  .gitignore
  README.md
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/Components/Common/Button.js
  src/Components/Header/HeaderContainer.js
  src/Components/Header/HeaderPresentational.js
  src/Components/Header/TodoCard.js
  src/Components/PopupMessage/PopupMessage.js
  src/Components/SideNavigator/SideNavigator.js
  src/Components/TodoCard/TodoCardContainer.js
  src/Components/TodoCard/TodoCardPresentational.js
  src/Components/TodoCard/const.js
  src/Components/TodoColumn/TodoColumnContainer.js
  src/Components/TodoColumn/TodoColumnPresentational.js
  src/Components/TodoColumnList/TodoColumnListContainer.js
  src/Pages/MainPage.js
  src/index.css
  src/index.js
  src/util/API.js
  yarn.lock
Labels: review-fe

#14 [BE] Team-12: To-Do List #1
  README.md
  be/README.md
  be/todo/.gitignore
  be/todo/build.gradle
  be/todo/gradle/wrapper/gradle-wrapper.jar
  be/todo/gradle/wrapper/gradle-wrapper.properties
  be/todo/gradlew
  be/todo/gradlew.bat
  be/todo/settings.gradle
  be/todo/src/main/java/com/codesquad/todo/TodoApplication.java
  be/todo/src/main/java/com/codesquad/todo/web/controller/ColumnController.java
  be/todo/src/main/java/com/codesquad/todo/web/controller/TaskController.java
  be/todo/src/main/java/com/codesquad/todo/web/controller/TodoLogController.java
  be/todo/src/main/java/com/codesquad/todo/web/controller/UserController.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/Column.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/Task.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/TodoLog.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/User.java
  be/todo/src/main/java/com/codesquad/todo/web/service/dto/ColumnDto.java
  be/todo/src/main/java/com/codesquad/todo/web/service/dto/TaskDto.java
  be/todo/src/main/java/com/codesquad/todo/web/service/dto/TodoLogDto.java
  be/todo/src/main/resources/application.properties
  be/todo/src/test/java/com/codesquad/todo/TodoApplicationTests.java
  fe/readme.md
Labels: review-be

#18 [FE] Team-16: To-Do List #1
  .DS_Store
  FE/.env
  FE/.gitignore
  FE/jsconfig.json
  FE/package-lock.json
  FE/package.json
  FE/public/data.json
  FE/public/index.html
  FE/src/App.css
  FE/src/App.js
  FE/src/App.test.js
  FE/src/components/Header/Header.css
  FE/src/components/Header/Header.jsx
  FE/src/components/TodoList/Columns.jsx
  FE/src/components/TodoList/Form.jsx
  FE/src/components/TodoList/TodoList.css
  FE/src/components/TodoList/TodoStore.jsx
  FE/src/components/TodoList/columnStyle.jsx
  FE/src/components/atoms/ButtonIcon.jsx
  FE/src/components/atoms/Card.jsx
  FE/src/components/atoms/ColumnHeader.jsx
  FE/src/components/atoms/Menu.css
  FE/src/components/atoms/Menu.jsx
  FE/src/index.css
  FE/src/index.js
  FE/src/reportWebVitals.js
  FE/src/reset.css
  FE/src/setupTests.js
  README.md
Labels: review-fe

#23 [FE] Team 13 - ToDo List Step1
  README.md
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/common/StyledModels.js
  frontend/src/components/header/Activity.js
  frontend/src/components/header/Header.js
  frontend/src/components/header/partial/ActivityCloseButton.js
  frontend/src/components/header/partial/ActivityItem.js
  frontend/src/components/header/partial/HeaderMenuButton.js
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Column.js
  frontend/src/components/main/Main.js
  frontend/src/components/main/partial/ColumnAccentButton.js
  frontend/src/components/main/partial/ColumnDeleteButton.js
  frontend/src/components/main/partial/ColumnNormalButton.js
  frontend/src/components/main/partial/ColumnPlusButton.js
  frontend/src/containers/column/ColumnContainer.js
  frontend/src/containers/header/HeaderContainer.js
  frontend/src/containers/main/MainContainer.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: review-fe

#24 [FE][d-dela-mi] 첫 번째 PR
  README.md
  todolist/.gitignore
  todolist/README.md
  todolist/package-lock.json
  todolist/package.json
  todolist/public/crong.jpg
  todolist/public/favicon.ico
  todolist/public/index.html
  todolist/src/App.css
  todolist/src/App.jsx
  todolist/src/App.test.js
  todolist/src/components/card/Card.jsx
  todolist/src/components/card/CardForm.jsx
  todolist/src/components/card/CardList.jsx
  todolist/src/components/card/CardWrap.jsx
  todolist/src/components/navBar/LogCommit.jsx
  todolist/src/components/navBar/LogStorage.jsx
  todolist/src/components/navBar/NavBar.jsx
  todolist/src/components/navBar/crong.jpg
  todolist/src/components/utils/IconButton.jsx
  todolist/src/components/utils/TextButton.jsx
  todolist/src/components/utils/constant.js
  todolist/src/index.css
  todolist/src/index.js
  todolist/yarn.lock
Labels: review-fe

#29 [FE][Kyle, Jenny, Pyro] 04/13 진행중...
  frontend/todo-frontend/package.json
  frontend/todo-frontend/public/Vector (2).svg
  frontend/todo-frontend/public/Vector.svg
  frontend/todo-frontend/public/plus.svg
  frontend/todo-frontend/src/App.js
  frontend/todo-frontend/src/component/TodoTemplate.jsx
  frontend/todo-frontend/src/component/TodoView.jsx
  frontend/todo-frontend/src/component/atom/Button.jsx
  frontend/todo-frontend/src/component/atom/DeleteBtn.jsx
  frontend/todo-frontend/src/component/atom/Input.jsx
  frontend/todo-frontend/src/component/atom/PopUp.jsx
  frontend/todo-frontend/src/component/todoHeader/TodoHeader.jsx
  frontend/todo-frontend/src/component/todoHeader/TodoLog.jsx
  frontend/todo-frontend/src/component/todoHeader/TodoNavBar.jsx
  frontend/todo-frontend/src/component/todoMain/TodoMain.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/TodoItem.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/TodoList.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/TodoListForm.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/todoList.module.css
  frontend/todo-frontend/src/component/todoMain/todoMain.module.css
  frontend/todo-frontend/src/hook/logHook.js
  frontend/todo-frontend/src/index.css
  frontend/todo-frontend/src/service/initTodoService.js
  frontend/todo-frontend/src/service/logService.js
  frontend/todo-frontend/src/service/todoListService.js
  frontend/todo-frontend/yarn.lock
Labels: review-fe

#30 [FE] [TEAM21] UI 및 이벤트 구현
  .gitignore
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/Component/Button.jsx
  src/Component/Header/HeadeTitle.jsx
  src/Component/Header/Header.jsx
  src/Component/Header/HistoryItem.jsx
  src/Component/Header/HistoryList.jsx
  src/Component/Header/Navigator.jsx
  src/Component/Todo/CreateTodo.jsx
  src/Component/Todo/TodoColumn.jsx
  src/Component/Todo/TodoColumnHead.jsx
  src/Component/Todo/TodoContainer.jsx
  src/Component/Todo/TodoItem.jsx
  src/Component/Todo/test.json
  src/hooks/README.md
  src/index.css
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: review-fe

#34 [FE][d-dela-mi] UI 추가 구현 중, 범용 Button 컴포넌트 작성 중..
  README.md
  package-lock.json
  todolist/src/App.css
  todolist/src/App.jsx
  todolist/src/components/Board.jsx
  todolist/src/components/StateProvider.jsx
  todolist/src/components/card/Card.jsx
  todolist/src/components/card/CardForm.jsx
  todolist/src/components/card/CardList.jsx
  todolist/src/components/card/CardWrap.jsx
  todolist/src/components/column/Column.jsx
  todolist/src/components/column/card/Card.jsx
  todolist/src/components/column/card/CardButton.style.jsx
  todolist/src/components/column/card/CardContainer.style.jsx
  todolist/src/components/column/card/CardForm.jsx
  todolist/src/components/column/card/CardList.jsx
  todolist/src/components/column/card/CardWrap.jsx
  todolist/src/components/navBar/LogCommit.jsx
  todolist/src/components/navBar/LogMessage.jsx
  todolist/src/components/navBar/LogStorage.jsx
  todolist/src/components/navBar/NavBar.jsx
  todolist/src/components/utils/Button.jsx
  todolist/src/components/utils/IconButton.jsx
  todolist/src/components/utils/TextButton.jsx
  todolist/src/components/utils/constant.js
Labels: review-fe

#25 [Team08-iOS] To-do List #1
  .gitignore
  README.md
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/team08/todolist/TodoListApplication.java
  backend/src/main/java/com/team08/todolist/config/ApplicationConfig.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/team08/todolist/TodoListApplicationTests.java
  frontend/README.md
  frontend/ToDoListApp/.DS_Store
  frontend/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  frontend/ToDoListApp/ToDoListApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  frontend/ToDoListApp/ToDoListApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  frontend/ToDoListApp/ToDoListApp.xcodeproj/project.xcworkspace/xcuserdata/idahun.xcuserdatad/UserInterfaceState.xcuserstate
  frontend/ToDoListApp/ToDoListApp.xcodeproj/xcuserdata/idahun.xcuserdatad/xcschemes/xcschememanagement.plist
  frontend/ToDoListApp/ToDoListApp.xcodeproj/xcuserdata/parkjungha.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  frontend/ToDoListApp/ToDoListApp.xcodeproj/xcuserdata/parkjungha.xcuserdatad/xcschemes/xcschememanagement.plist
  frontend/ToDoListApp/ToDoListApp/AppDelegate.swift
  frontend/ToDoListApp/ToDoListApp/Assets.xcassets/AccentColor.colorset/Contents.json
  frontend/ToDoListApp/ToDoListApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  frontend/ToDoListApp/ToDoListApp/Assets.xcassets/Contents.json
  frontend/ToDoListApp/ToDoListApp/Base.lproj/LaunchScreen.storyboard
  frontend/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/CardAddManager.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ColumnDataSource.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ColumnDelegate.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ColumnView.storyboard
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ColumnViewController.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ContentTextFieldDelegate.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ModalViewController.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/TitleTextFieldDelegate.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Model/CellData.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Model/ColumnDatas.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/Model/DataManager.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/View/Badge.swift
  frontend/ToDoListApp/ToDoListApp/ColumnSection/View/ColumnCell.swift
  frontend/ToDoListApp/ToDoListApp/Info.plist
  frontend/ToDoListApp/ToDoListApp/SceneDelegate.swift
  frontend/ToDoListApp/ToDoListApp/Service/MockNetworkService.swift
  frontend/ToDoListApp/ToDoListApp/Service/NetworkService.swift
  frontend/ToDoListApp/ToDoListApp/Service/PositionManager.swift
  frontend/ToDoListApp/ToDoListApp/ViewController.swift
  frontend/ToDoListApp/ToDoListAppTests/Info.plist
  frontend/ToDoListApp/ToDoListAppTests/NetworkServiceTests.swift
  frontend/ToDoListApp/ToDoListAppTests/PositionManagerTests.swift
  frontend/ToDoListApp/ToDoListAppTests/ToDoListAppTests.swift
  frontend/ToDoListApp/ToDoListAppUITests/Info.plist
  frontend/ToDoListApp/ToDoListAppUITests/ToDoListAppUITests.swift
Labels: review-ios

#31 [iOS][Ray, V] todoList add, delete 동작구현
  .gitignore
  README.md
  iOS/.gitignore
  iOS/README.md
  iOS/TodoApp/Controller/MainViewController.swift
  iOS/TodoApp/Controller/NewTaskCardViewController.swift
  iOS/TodoApp/Controller/NewTaskViewController.swift
  iOS/TodoApp/Controller/Task/TaskDataSource.swift
  iOS/TodoApp/Controller/Task/TaskDelegate.swift
  iOS/TodoApp/Controller/Task/TaskViewController.swift
  iOS/TodoApp/Controller/TaskCard.swift
  iOS/TodoApp/Enum/Constant.swift
  iOS/TodoApp/Enum/SegueInfo.swift
  iOS/TodoApp/Model/Network/NetworkManager.swift
  iOS/TodoApp/Model/TaskCard.swift
  iOS/TodoApp/Model/TaskStack.swift
  iOS/TodoApp/Model/TaskStackManager.swift
  iOS/TodoApp/Stroyboard/Base.lproj/LaunchScreen.storyboard
  iOS/TodoApp/Stroyboard/Base.lproj/Main.storyboard
  iOS/TodoApp/TaskCards.swift
  iOS/TodoApp/TaskCardsManager.swift
  iOS/TodoApp/TodoApp.xcodeproj/project.pbxproj
  iOS/TodoApp/TodoApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/TodoApp/TodoApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/TodoApp/TodoApp.xcodeproj/project.xcworkspace/xcuserdata/kimjisun.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/TodoApp/TodoApp.xcodeproj/project.xcworkspace/xcuserdata/ray.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/TodoApp/TodoApp.xcodeproj/xcuserdata/kimjisun.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  iOS/TodoApp/TodoApp.xcodeproj/xcuserdata/kimjisun.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/TodoApp/TodoApp.xcodeproj/xcuserdata/ray.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  iOS/TodoApp/TodoApp.xcodeproj/xcuserdata/ray.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/TodoApp/TodoApp/AppDelegate.swift
  iOS/TodoApp/TodoApp/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/TodoApp/TodoApp/Assets.xcassets/AppIcon.appiconset/20.png
  iOS/TodoApp/TodoApp/Assets.xcassets/AppIcon.appiconset/40.png
  iOS/TodoApp/TodoApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/TodoApp/TodoApp/Assets.xcassets/Contents.json
  iOS/TodoApp/TodoApp/Assets.xcassets/codesquad.imageset/Contents.json
  iOS/TodoApp/TodoApp/Assets.xcassets/codesquad.imageset/codesquad2-1.png
  iOS/TodoApp/TodoApp/Assets.xcassets/codesquad.imageset/codesquad2-2.png
  iOS/TodoApp/TodoApp/Assets.xcassets/codesquad.imageset/codesquad2.png
  iOS/TodoApp/TodoApp/Assets.xcassets/launchImage.imageset/Contents.json
  iOS/TodoApp/TodoApp/Assets.xcassets/launchImage.imageset/launchImage-1.png
  iOS/TodoApp/TodoApp/Assets.xcassets/launchImage.imageset/launchImage-2.png
  iOS/TodoApp/TodoApp/Assets.xcassets/launchImage.imageset/launchImage.png
  iOS/TodoApp/TodoApp/Info.plist
  iOS/TodoApp/TodoApp/SceneDelegate.swift
  iOS/TodoApp/TodoAppTests/Info.plist
  iOS/TodoApp/TodoAppTests/TodoAppTests.swift
  iOS/TodoApp/TodoAppUITests/Info.plist
  iOS/TodoApp/TodoAppUITests/TodoAppUITests.swift
  iOS/TodoApp/View/TaskCell.swift
  iOS/TodoApp/View/TaskCell.xib
Labels: review-ios

#32 [iOS][Min&Lia] - TableViewController 재사용, 카드 Add 및 Drag&Drop 구현
  .DS_Store
  .gitignore
  README.md
  Todo_List/.DS_Store
  Todo_List/Todo_List.xcodeproj/project.pbxproj
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/xcuserdata/gimjigyeong.xcuserdatad/UserInterfaceState.xcuserstate
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/xcuserdata/shim.xcuserdatad/UserInterfaceState.xcuserstate
  Todo_List/Todo_List.xcodeproj/xcuserdata/gimjigyeong.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Todo_List/Todo_List.xcodeproj/xcuserdata/gimjigyeong.xcuserdatad/xcschemes/xcschememanagement.plist
  Todo_List/Todo_List.xcodeproj/xcuserdata/shim.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Todo_List/Todo_List.xcodeproj/xcuserdata/shim.xcuserdatad/xcschemes/xcschememanagement.plist
  Todo_List/Todo_List/Base.lproj/Main.storyboard
  Todo_List/Todo_List/Controller/TodoDataSource.swift
  Todo_List/Todo_List/Controller/TodoDelegate.swift
  Todo_List/Todo_List/Controller/TodoTableViewController.swift
  Todo_List/Todo_List/Controller/TodoTableViewDragDelegate.swift
  Todo_List/Todo_List/Controller/TodoTableViewDropDelegate.swift
  Todo_List/Todo_List/Controller/ViewController.swift
  Todo_List/Todo_List/Etc/AppDelegate.swift
  Todo_List/Todo_List/Etc/Assets.xcassets/AccentColor.colorset/Contents.json
  Todo_List/Todo_List/Etc/Assets.xcassets/AppIcon.appiconset/Contents.json
  Todo_List/Todo_List/Etc/Assets.xcassets/Contents.json
  Todo_List/Todo_List/Etc/Base.lproj/LaunchScreen.storyboard
  Todo_List/Todo_List/Etc/Info.plist
  Todo_List/Todo_List/Etc/SceneDelegate.swift
  Todo_List/Todo_List/Extension/AddLineSpacing.swift
  Todo_List/Todo_List/ModalView/ModalTextViewDelegate.swift
  Todo_List/Todo_List/ModalView/ModalViewController.swift
  Todo_List/Todo_List/ModalView/ModalViewController.xib
  Todo_List/Todo_List/Model/CardManager.swift
  Todo_List/Todo_List/Model/TodoCard.swift
  Todo_List/Todo_List/Model/TodoCards.swift
  Todo_List/Todo_List/Model/User.swift
  Todo_List/Todo_List/View/TodoCell.swift
  Todo_List/Todo_List/View/TodoCell.xib
  Todo_List/Todo_ListTests/Info.plist
  Todo_List/Todo_ListTests/Todo_ListTests.swift
  Todo_List/Todo_ListUITests/Info.plist
  Todo_List/Todo_ListUITests/Todo_ListUITests.swift
Labels: review-ios

#12 [team02-BE] TO-DO 리스트 프로젝트 1주차 PR 드립니다.
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  .idea/todo-list.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  backend/todo-list/.gitignore
  backend/todo-list/build.gradle
  backend/todo-list/gradle/wrapper/gradle-wrapper.jar
  backend/todo-list/gradle/wrapper/gradle-wrapper.properties
  backend/todo-list/gradlew
  backend/todo-list/gradlew.bat
  backend/todo-list/settings.gradle
  backend/todo-list/src/main/java/com/example/todolist/TodoListApplication.java
  backend/todo-list/src/main/java/com/example/todolist/WebConfig.java
  backend/todo-list/src/main/java/com/example/todolist/common/CustomHandlerMethodArgumentResolver.java
  backend/todo-list/src/main/java/com/example/todolist/common/CustomResolver.java
  backend/todo-list/src/main/java/com/example/todolist/common/JwtAuthInterceptor.java
  backend/todo-list/src/main/java/com/example/todolist/common/JwtUtil.java
  backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
  backend/todo-list/src/main/java/com/example/todolist/controller/HomeController.java
  backend/todo-list/src/main/java/com/example/todolist/domain/Card.java
  backend/todo-list/src/main/java/com/example/todolist/domain/History.java
  backend/todo-list/src/main/java/com/example/todolist/domain/User.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CardDTO.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CardLogDTO.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CategoryDTO.java
  backend/todo-list/src/main/java/com/example/todolist/dto/HistoryDTO.java
  backend/todo-list/src/main/java/com/example/todolist/exception/CardNotFoundException.java
  backend/todo-list/src/main/java/com/example/todolist/exception/ElementNotFoundException.java
  backend/todo-list/src/main/java/com/example/todolist/exception/GlobalExceptionHandler.java
  backend/todo-list/src/main/java/com/example/todolist/exception/IllegalUserAccessException.java
  backend/todo-list/src/main/java/com/example/todolist/exception/UserNotFoundException.java
  backend/todo-list/src/main/java/com/example/todolist/repository/CardRepository.java
  backend/todo-list/src/main/java/com/example/todolist/repository/HistoryRepository.java
  backend/todo-list/src/main/java/com/example/todolist/repository/UserRepository.java
  backend/todo-list/src/main/java/com/example/todolist/service/CardService.java
  backend/todo-list/src/main/java/com/example/todolist/service/HistoryService.java
  backend/todo-list/src/main/java/com/example/todolist/service/UserService.java
  backend/todo-list/src/main/resources/application.properties
  backend/todo-list/src/main/resources/data.sql
  backend/todo-list/src/main/resources/schema.sql
Labels: review-be

#47 [FE] Team 13 - ToDo List Step2
  frontend/package.json
  frontend/public/images/smile.png
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/common/AccentButton.js
  frontend/src/components/common/CommonStyledComponent.js
  frontend/src/components/common/NormalButton.js
  frontend/src/components/common/PopupModal.js
  frontend/src/components/header/Activity.js
  frontend/src/components/header/partial/ActivityItem.js
  frontend/src/components/main/Card.js
  frontend/src/components/main/CardInput.js
  frontend/src/components/main/Main.js
  frontend/src/components/main/column/Column.js
  frontend/src/components/main/column/ColumnDeleteButton.js
  frontend/src/components/main/column/ColumnPlusButton.js
  frontend/src/components/main/column/card/Card.js
  frontend/src/components/main/column/card/CardInput.js
  frontend/src/components/topbar/Activity/Activity.js
  frontend/src/components/topbar/Activity/ActivityCloseButton.js
  frontend/src/components/topbar/Activity/ActivityItem.js
  frontend/src/components/topbar/Header/Header.js
  frontend/src/components/topbar/Header/HeaderMenuButton.js
  frontend/src/components/topbar/TopbarTemplate.js
  frontend/src/containers/column/ColumnContainer.js
  frontend/src/containers/header/HeaderContainer.js
  frontend/src/containers/main/MainContainer.js
  frontend/src/containers/main/column/ColumnContainer.js
  frontend/src/containers/main/column/card/CardContainer.js
  frontend/src/containers/main/column/card/CardInputContainer.js
  frontend/src/containers/topbar/TopbarContainer.js
  frontend/src/containers/topbar/tempData.json
  frontend/src/lib/utility/util.js
  frontend/src/setupProxy.js
Labels: review-fe

#51 [FE][d-dela-mi] mogoDB 연결, 드래그 앤 드롭, 로그 기록 등 구현
  todolist/.gitignore
  todolist/DB.js
  todolist/mySchema.js
  todolist/package-lock.json
  todolist/package.json
  todolist/router.js
  todolist/server.js
  todolist/src/App.css
  todolist/src/App.jsx
  todolist/src/components/Board.jsx
  todolist/src/components/StateProvider.jsx
  todolist/src/components/column/Column.jsx
  todolist/src/components/column/card/Card.jsx
  todolist/src/components/column/card/CardForm.jsx
  todolist/src/components/column/card/CardList.jsx
  todolist/src/components/column/card/CardWrap.jsx
  todolist/src/components/navBar/LogCommit.jsx
  todolist/src/components/navBar/LogMessage.jsx
  todolist/src/components/navBar/LogStorage.jsx
  todolist/src/components/navBar/NavBar.jsx
  todolist/src/components/utils/Button.jsx
  todolist/src/components/utils/constant.js
  todolist/yarn.lock
Labels: review-fe

#15 [BE]Team-06: To-Do-List #1
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/team06/todo/TodoApplication.java
  backend/src/main/java/com/team06/todo/controller/ActionsController.java
  backend/src/main/java/com/team06/todo/controller/CardsController.java
  backend/src/main/java/com/team06/todo/domain/Action.java
  backend/src/main/java/com/team06/todo/domain/ActionType.java
  backend/src/main/java/com/team06/todo/domain/Card.java
  backend/src/main/java/com/team06/todo/dto/ActionResponseDto.java
  backend/src/main/java/com/team06/todo/dto/ActionsResponse.java
  backend/src/main/java/com/team06/todo/dto/CardCreateRequestDto.java
  backend/src/main/java/com/team06/todo/dto/CardMoveRequestDto.java
  backend/src/main/java/com/team06/todo/dto/CardResponseDto.java
  backend/src/main/java/com/team06/todo/dto/CardUpdateRequestDto.java
  backend/src/main/java/com/team06/todo/dto/CardsResponse.java
  backend/src/main/java/com/team06/todo/repository/ActionsRepository.java
  backend/src/main/java/com/team06/todo/repository/CardsRepository.java
  backend/src/main/java/com/team06/todo/service/ActionsService.java
  backend/src/main/java/com/team06/todo/service/CardsService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: review-be

#27 [BE][Team-03] todolist 구현
  README.md
  backend/.gitignore
  backend/README.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/codeSquad/cocokyu/CocoKyuApplication.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/CardController.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/CardRepository.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/CardService.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/LogRepository.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/annotation/ToDoStatusPattern.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/annotation/ToDoStatusPatternValidator.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/dto/CardDto.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/dto/CardList.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/dto/LogList.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/model/Card.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/model/Log.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/model/Logs.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/model/Message.java
  backend/src/main/java/com/codeSquad/cocokyu/domain/model/Status.java
  backend/src/main/resources/application.properties
  ios/sam.txt
Labels: review-be

#43 [BE] [team-9 아이작 & 노을] todo-list API 구현
  .gitignore
  BE/ERD.mwb
  BE/todo/build.gradle
  BE/todo/gradle/wrapper/gradle-wrapper.jar
  BE/todo/gradle/wrapper/gradle-wrapper.properties
  BE/todo/gradlew
  BE/todo/gradlew.bat
  BE/todo/settings.gradle
  BE/todo/src/main/java/team9/todo/TodoApplication.java
  BE/todo/src/main/java/team9/todo/config/JdbcConfig.java
  BE/todo/src/main/java/team9/todo/controller/ApiCardController.java
  BE/todo/src/main/java/team9/todo/controller/ApiHistoryController.java
  BE/todo/src/main/java/team9/todo/controller/ApiUserController.java
  BE/todo/src/main/java/team9/todo/controller/GlobalApiExceptionHandler.java
  BE/todo/src/main/java/team9/todo/domain/ApiResult.java
  BE/todo/src/main/java/team9/todo/domain/Card.java
  BE/todo/src/main/java/team9/todo/domain/DTO/Card/RequestCreateDTO.java
  BE/todo/src/main/java/team9/todo/domain/DTO/Card/RequestMoveDTO.java
  BE/todo/src/main/java/team9/todo/domain/DTO/Card/RequestUpdateDTO.java
  BE/todo/src/main/java/team9/todo/domain/DTO/Card/ResponseDTO.java
  BE/todo/src/main/java/team9/todo/domain/History.java
  BE/todo/src/main/java/team9/todo/domain/HistoryWithCardTitle.java
  BE/todo/src/main/java/team9/todo/domain/User.java
  BE/todo/src/main/java/team9/todo/domain/enums/CardColumn.java
  BE/todo/src/main/java/team9/todo/domain/enums/HistoryAction.java
  BE/todo/src/main/java/team9/todo/exception/NotAuthorizedException.java
  BE/todo/src/main/java/team9/todo/exception/NotFoundException.java
  BE/todo/src/main/java/team9/todo/repository/CardRepository.java
  BE/todo/src/main/java/team9/todo/repository/HistoryRepository.java
  BE/todo/src/main/java/team9/todo/repository/UserRepository.java
  BE/todo/src/main/java/team9/todo/service/CardService.java
  BE/todo/src/main/java/team9/todo/service/HistoryService.java
  BE/todo/src/main/java/team9/todo/utils/HttpSessionUtils.java
  BE/todo/src/main/resources/application.properties
  BE/todo/src/main/resources/data.sql
  BE/todo/src/main/resources/schema.sql
  BE/todo/src/test/java/team9/todo/TodoApplicationTests.java
  BE/todo/src/test/java/team9/todo/controller/ApiCardControllerTest.java
  Doc/ERD.png
Labels: review-be

#44 [BE] Team10 - Marco, Dong todo-list 구현 PR 요청드립니다!
  README.md
  backend/.DS_Store
  backend/todolist/.gitignore
  backend/todolist/.idea/.gitignore
  backend/todolist/.idea/compiler.xml
  backend/todolist/.idea/gradle.xml
  backend/todolist/.idea/jarRepositories.xml
  backend/todolist/.idea/misc.xml
  backend/todolist/.idea/uiDesigner.xml
  backend/todolist/.idea/vcs.xml
  backend/todolist/build.gradle
  backend/todolist/gradle/wrapper/gradle-wrapper.jar
  backend/todolist/gradle/wrapper/gradle-wrapper.properties
  backend/todolist/gradlew
  backend/todolist/gradlew.bat
  backend/todolist/settings.gradle
  backend/todolist/src/main/java/team10/todolist/Action.java
  backend/todolist/src/main/java/team10/todolist/Category.java
  backend/todolist/src/main/java/team10/todolist/TodolistApplication.java
  backend/todolist/src/main/java/team10/todolist/controller/BoardController.java
  backend/todolist/src/main/java/team10/todolist/controller/LogController.java
  backend/todolist/src/main/java/team10/todolist/domain/Board.java
  backend/todolist/src/main/java/team10/todolist/domain/Log.java
  backend/todolist/src/main/java/team10/todolist/dto/BoardDto.java
  backend/todolist/src/main/java/team10/todolist/repository/BoardRepository.java
  backend/todolist/src/main/java/team10/todolist/repository/LogRepository.java
  backend/todolist/src/main/java/team10/todolist/service/BoardService.java
  backend/todolist/src/main/java/team10/todolist/service/LogService.java
  backend/todolist/src/main/resources/application.properties
  backend/todolist/src/main/resources/static/index.html
  backend/todolist/src/test/java/team10/todolist/TodolistApplicationTests.java
Labels: review-be

#52 [BE][TEAM-02, Jane&Robin] 2번째 PR 요청드립니다.
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  .idea/todo-list.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  backend/todo-list/.gitignore
  backend/todo-list/build.gradle
  backend/todo-list/gradle/wrapper/gradle-wrapper.jar
  backend/todo-list/gradle/wrapper/gradle-wrapper.properties
  backend/todo-list/gradlew
  backend/todo-list/gradlew.bat
  backend/todo-list/settings.gradle
  backend/todo-list/src/main/java/com/example/todolist/TodoListApplication.java
  backend/todo-list/src/main/java/com/example/todolist/WebConfig.java
  backend/todo-list/src/main/java/com/example/todolist/common/CustomHandlerMethodArgumentResolver.java
  backend/todo-list/src/main/java/com/example/todolist/common/CustomResolver.java
  backend/todo-list/src/main/java/com/example/todolist/common/JwtAuthInterceptor.java
  backend/todo-list/src/main/java/com/example/todolist/common/JwtUtil.java
  backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
  backend/todo-list/src/main/java/com/example/todolist/controller/HomeController.java
  backend/todo-list/src/main/java/com/example/todolist/domain/Card.java
  backend/todo-list/src/main/java/com/example/todolist/domain/History.java
  backend/todo-list/src/main/java/com/example/todolist/domain/User.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CardDTO.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CardLogDTO.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CategoryDTO.java
  backend/todo-list/src/main/java/com/example/todolist/dto/HistoryDTO.java
  backend/todo-list/src/main/java/com/example/todolist/exception/CardNotFoundException.java
  backend/todo-list/src/main/java/com/example/todolist/exception/ElementNotFoundException.java
  backend/todo-list/src/main/java/com/example/todolist/exception/GlobalExceptionHandler.java
  backend/todo-list/src/main/java/com/example/todolist/exception/IllegalUserAccessException.java
  backend/todo-list/src/main/java/com/example/todolist/exception/UserNotFoundException.java
  backend/todo-list/src/main/java/com/example/todolist/repository/CardRepository.java
  backend/todo-list/src/main/java/com/example/todolist/repository/HistoryRepository.java
  backend/todo-list/src/main/java/com/example/todolist/repository/UserRepository.java
  backend/todo-list/src/main/java/com/example/todolist/service/CardService.java
  backend/todo-list/src/main/java/com/example/todolist/service/HistoryService.java
  backend/todo-list/src/main/java/com/example/todolist/service/UserService.java
  backend/todo-list/src/main/resources/application.properties
  backend/todo-list/src/main/resources/data.sql
  backend/todo-list/src/main/resources/schema.sql
Labels: review-be

#58 [(FE)team15: pyro, kyle, jenny] 마무리
  frontend/todo-frontend/src/component/TodoView.jsx
  frontend/todo-frontend/src/component/atom/DeleteBtn.jsx
  frontend/todo-frontend/src/component/atom/Input.jsx
  frontend/todo-frontend/src/component/atom/PopUp.jsx
  frontend/todo-frontend/src/component/todoHeader/TodoHeader.jsx
  frontend/todo-frontend/src/component/todoHeader/TodoLog.jsx
  frontend/todo-frontend/src/component/todoHeader/TodoNavBar.jsx
  frontend/todo-frontend/src/component/todoMain/TodoMain.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/TodoItem.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/TodoList.jsx
  frontend/todo-frontend/src/component/todoMain/todoList/TodoListForm.jsx
  frontend/todo-frontend/src/hook/dataHook.js
  frontend/todo-frontend/src/hook/logHook.js
  frontend/todo-frontend/src/hook/todoHook.js
  frontend/todo-frontend/src/service/initTodoService.js
  frontend/todo-frontend/src/service/todoListService.js
  frontend/todo-frontend/src/util/util.js
Labels: review-fe

#59 [FE][d-dela-mi] 최종 제출
  todolist/mySchema.js
  todolist/package-lock.json
  todolist/router.js
  todolist/src/components/Board.jsx
  todolist/src/components/column/Column.jsx
  todolist/src/components/column/ColumnWrap.jsx
  todolist/src/components/column/card/Card.jsx
  todolist/src/components/column/card/CardButton.style.jsx
  todolist/src/components/column/card/CardButtonSection.style.jsx
  todolist/src/components/column/card/CardForm.jsx
  todolist/src/components/navBar/LogMessage.jsx
  todolist/src/components/navBar/LogStorage.jsx
  todolist/src/components/navBar/NavBar.jsx
  todolist/src/components/utils/Button.jsx
  todolist/src/components/utils/constant.js
Labels: review-fe

#53 [BE] [Team-08] ToDo-list 최종 구현
  backend/build.gradle
  backend/src/main/java/com/team08/todolist/ColumnType.java
  backend/src/main/java/com/team08/todolist/config/ApplicationConfig.java
  backend/src/main/java/com/team08/todolist/controller/ApiCardController.java
  backend/src/main/java/com/team08/todolist/controller/ApiHistoryController.java
  backend/src/main/java/com/team08/todolist/controller/ApiResponse.java
  backend/src/main/java/com/team08/todolist/controller/ApiUserController.java
  backend/src/main/java/com/team08/todolist/dto/CardDto.java
  backend/src/main/java/com/team08/todolist/dto/HistoryDto.java
  backend/src/main/java/com/team08/todolist/model/Card.java
  backend/src/main/java/com/team08/todolist/model/History.java
  backend/src/main/java/com/team08/todolist/model/User.java
  backend/src/main/java/com/team08/todolist/repository/CardRepository.java
  backend/src/main/java/com/team08/todolist/repository/HistoryRepository.java
  backend/src/main/java/com/team08/todolist/service/CardService.java
  backend/src/main/java/com/team08/todolist/service/HistoryService.java
  backend/src/main/java/com/team08/todolist/util/DateTimeUtils.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/banner.txt
Labels: review-be

#63 [FE] [TEAM21] 마무리
  README.md
  package-lock.json
  package.json
  src/App.js
  src/Component/Context.jsx
  src/Component/Header/CreateColumn.jsx
  src/Component/Header/HeadeTitle.jsx
  src/Component/Header/Header.jsx
  src/Component/Header/HistoryItem.jsx
  src/Component/Header/HistoryList.jsx
  src/Component/Header/Navigator.jsx
  src/Component/Header/Popup.jsx
  src/Component/Todo/CreateTodo.jsx
  src/Component/Todo/EditTodo.jsx
  src/Component/Todo/TodoColumn.jsx
  src/Component/Todo/TodoColumnHead.jsx
  src/Component/Todo/TodoContainer.jsx
  src/Component/Todo/TodoItem.jsx
  src/Component/Todo/test.json
  src/api.js
Labels: review-fe
